'''

https://leetcode.com/problems/find-the-difference/ 

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

s - abcd
t - abcde,  

1. Sort
2. 

'''

def findTheDifference(s,t):
    s = ''.join(sorted(s))
    t = ''.join(sorted(t))
    

    s_len = len(s)


    for i in range(s_len):
        if s[i] != t[i]:
            return t[i]
    return t[-1]


# print(findTheDifference("abcd", "abcde"))
print(findTheDifference("", "y"))